const fontawesome = require('@fortawesome/fontawesome')
const faTwitter = require('@fortawesome/fontawesome-free-brands/faTwitter')
const faMediumM = require('@fortawesome/fontawesome-free-brands/faMediumM')
const faSlackHash = require('@fortawesome/fontawesome-free-brands/faSlackHash')
const faGoogle = require('@fortawesome/fontawesome-free-brands/faGoogle')
const faLinkedinIn = require('@fortawesome/fontawesome-free-brands/faLinkedinIn')
const faGithub = require('@fortawesome/fontawesome-free-brands/faGithub')

fontawesome.library.add(faTwitter)
fontawesome.library.add(faMediumM)
fontawesome.library.add(faSlackHash)
fontawesome.library.add(faGoogle)
fontawesome.library.add(faLinkedinIn)
fontawesome.library.add(faGithub)
